import com.github.spotbugs.snom.Confidence
import com.github.spotbugs.snom.Effort

plugins {
    id 'java'
    id 'jacoco'
    id 'com.github.spotbugs' version '6.5.6'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.mbi'
version = '0.0.1-SNAPSHOT'
description = 'ticketing-reservation'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

jacoco {
    toolVersion = '0.8.15'
}

spotbugs {
    ignoreFailures = true
    showProgress = false
    effort = Effort.valueOf('DEFAULT')
    reportLevel = Confidence.valueOf('HIGH')
}

repositories {
    mavenCentral()
}

def mapstructVersion = '1.6.3'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-liquibase'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-opentelemetry'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation "org.mapstruct:mapstruct:${mapstructVersion}"
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.1'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

    runtimeOnly 'com.h2database:h2'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    testAnnotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
    finalizedBy tasks.named('jacocoTestReport')
}

tasks.named('jacocoTestReport') {
    dependsOn tasks.named('test')
    reports {
        html.required = true
        xml.required = true
        csv.required = false
    }
}

tasks.named('spotbugsTest') {
    enabled = false
}

tasks.named('spotbugsMain') {
    reports {
        html {
            required = true
            outputLocation = layout.buildDirectory.file('reports/spotbugs/main/spotbugs.html')
            stylesheet = 'fancy-hist.xsl'
        }
        xml {
            required = true
            outputLocation = layout.buildDirectory.file('reports/spotbugs/main/spotbugs.xml')
        }
    }
}
